### ISSUE TITLE
Proposal to take over

### ISSUE THREAD

**Issue by riderx** [Cap-go/capacitor-data-storage-sqlite#74]
Hello Jean-Pierre,

First of all, thank you for the fantastic work done on this plugin and all the others you have created.

I saw your message on the README of the project and I hope that this time you take for yourself will allow you to maintain health for yourself and your loved ones.

I am the creator of Capgo, an open-source live update system on Capacitor.
I maintain a number of plugin forks from the community, this creates a virtuous circle for Capgo.
You can find them here: https://capgo.app/plugins/
I would like to become the main maintainer.

Let's call us to discuss it if you wish: https://cal.com/martindonadieu/meet

**Comment by jepiqueau** [comment]
Hello Martin,Thanks for your proposal. For this plugin i will agree to transfer the ownership to cargo so you can become the new owner. I am out right now without access to my Mac. I soon as i am available i will contact you. For sqlite as it is part of the capacitor-community i have to contact them first before taking the decision . Any how i will come back to you when available.RegardsJean Pierre ***@***.***÷33768267122Envoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : Martin DONADIEU ***@***.***> Date : 18/07/2024  14:57  (GMT+01:00) À : jepiqueau/capacitor-data-storage-sqlite ***@***.***> Cc : Subscribed ***@***.***> Objet : [jepiqueau/capacitor-data-storage-sqlite] Proposal to take over (Issue #74) 
Hello Jean-Pierre,
First of all, thank you for the fantastic work done on this plugin and all the others you have created.
I saw your message on the README of the project and I hope that this time you take for yourself will allow you to maintain health for yourself and your loved ones.
I am the creator of Capgo, an open-source live update system on Capacitor.
I maintain a number of plugin forks from the community, this creates a virtuous circle for Capgo.
You can find them here: https://capgo.app/plugins/
I would like to become the main maintainer.
Let's call us to discuss it if you wish: https://cal.com/martindonadieu/meet

**Comment by mburger81** [comment]
Hello, are there news about taking over this? @jepiqueau @riderx 

As a community project we are waiting hard for this to be maintained as in a few weeks we need capacitor@6 to be able to upload the app on the play store

**Comment by riderx** [comment]
@jepiqueau no problem, let's do one at the time if you want, then i make capacitor v6 on this one already and this will unlock some users

**Comment by mburger81** [comment]
@riderx that would be really great, thx you a lot!

As you have already said, bringing this to capacitor v6 will unlock a lot of projects.


But anyway IMO both of them are under MIT license, so you should be free to fork both and work on both without restrictions. Correct @jepiqueau

**Comment by riderx** [comment]
Yes i have done many fork with Capgo, but it takes time to get user trust and it kinda split the ecosystem. That why i propose always this first to maintain trust :)

**Comment by mburger81** [comment]
Yeah sure, but you @riderx are capgo so you already deserve all our trust :)

We have written an ionic super app which we have to launch soon for our internal testers so as you can think its relative urgent for us to have the plugin migrated.

We are obviously willed to contribute and would like to test the plugin on multiple devices and give you feedback.

**Comment by mburger81** [comment]
Just for interest,

would it not be good you just clone it on your own `cap-go` repository (as you already did) and you release it as `@capgo/capacitor-data-storage-sqlite` on npmjs. And at the end in this repo you just reference it as deprecated with the link the the new one?

It would be more difficult for us to run the migration because we need to do it manually, but the cut would be nicer IMO

just my opinion

**Comment by riderx** [comment]
@mburger81 It will at one point be on the Capgo org name on NPM, I think, but first we transfer the issue and the GitHub.

**Comment by jepiqueau** [comment]
@riderx i made the transfer on github can you accept it

**Comment by jepiqueau** [comment]
@riderx when done tell me so i can transfer the ownership on npm. Do not forget to tell users that you take the ownership on the readme

**Comment by riderx** [comment]
@jepiqueau I didn't receive any email, I think for org it's better if I add you first and then you initiate it.
I just invited you can you accept and try again?

**Comment by jepiqueau** [comment]
@riderx Where should i see your invitation

**Comment by jepiqueau** [comment]
@riderx my mistake i use Capgo and not Cap-go Now when i used Cap-go i got Cap-go/capacitor-data-storage-sqlite already exists and You don’t have the permission to create public repositories on Cap-go

**Comment by jepiqueau** [comment]
@riderx You have a fork with the same name in your repository so remove the fork first

**Comment by jepiqueau** [comment]
@riderx on npm your username is ~riderx not riderx

**Comment by riderx** [comment]
Ok i renamed the repo i have to Cap-go/capacitor-data-storage-sqlite_old
Can you try otherwise i will remove it
Invitation should be by email or here: https://github.com/orgs/Cap-go/people
For npm correct it was how the URL display

**Comment by jepiqueau** [comment]
@riderx the transfer of ownership is done

**Comment by jepiqueau** [comment]
@riderx i will do the one on npm. tell me if when you have published one if it has worked so i can remove myself as npm owner. I wish you all success and i am relay happy that you take the lead now for this plugin

**Comment by jepiqueau** [comment]
@ riderx my email is jepi.queau@free.fr

**Comment by jepiqueau** [comment]
@riderx i have successfully add you as an npm owner of this package

**Comment by riderx** [comment]
Thanks i'm testing it and keep you in touch !

**Comment by riderx** [comment]
Hey @jepiqueau, can you reconfirm for npm?
It seems i don't have the right to push
![CleanShot 2024-08-13 at 22 52 29@2x](https://github.com/user-attachments/assets/08917d16-74be-474f-9928-e0893881e14f)
I added CI/CD so it's easy to test any commit on main will trigger a publish

**Comment by riderx** [comment]
On another note, the doc makes reference to this:
### Ionic/Angular

- [angular-data-storage-sqlite-app-starter](https://github.com/jepiqueau/angular-data-storage-sqlite-app-starter)

### Ionic/React

- [react-data-storage-sqlite-app-starter](https://github.com/jepiqueau/react-data-storage-sqlite-app-starter)

### React

- [react-datastoragesqlite-app](https://github.com/jepiqueau/react-datastoragesqlite-app)

### Ionic/Vue

- [vue-data-storage-sqlite-app-starter](https://github.com/jepiqueau/vue-data-storage-sqlite-app-starter)

### Vue

- [vue-datastoragesqlite-app](https://github.com/jepiqueau/vue-datastoragesqlite-app)

Should we transfer it too?

**Comment by jepiqueau** [comment]
@riderx  Well i have done this npm owner add riderx capacitor-data-storage-sqlite
and i got this in reply Authenticate your account at:
https://www.npmjs.com/auth/cli/954eac1e-215b-426d-9ef1-8d600a190f82
Press ENTER to open in the browser...

npm notice INFO: User riderx invited to package capacitor-data-storage-sqlite successfully.
+ riderx (capacitor-data-storage-sqlite)
but when i do this npm owner ls capacitor-data-storage-sqlite i got jeepq <jeanpierre.queau@gmail.com>  so seems riderx was not added.
Looking to ChatGPT for the reason i got this
It seems that the riderx user was invited to become a maintainer of the capacitor-data-storage-sqlite package, but the invitation hasn't been accepted yet. This is why riderx does not appear in the list when you run the npm owner ls command.

Here’s what’s happening and how you can resolve it:

What Happened
When you executed the npm owner add riderx capacitor-data-storage-sqlite command, npm sent an invitation to the riderx user to become a maintainer of the package.
The user riderx needs to accept the invitation in order to be added as a maintainer.
Until riderx accepts the invitation, they won’t show up in the list of maintainers when you run npm owner ls capacitor-data-storage-sqlite.
What to Do Next
Ask riderx to Accept the Invitation:

The user riderx should check their email or log into their npm account on the [npm website](https://www.npmjs.com/).
They should see a notification or an invitation under their profile.
Once they accept the invitation, they will be added as a maintainer of the package.
Verify After Acceptance:

After riderx accepts the invitation, you can verify the addition by running:
bash
Copy code
npm owner ls capacitor-data-storage-sqlite
riderx should now appear in the list alongside the existing maintainers.
Additional Notes
Invitation Expiry: If the invitation isn't accepted within a certain period, it might expire, and you'll need to send it again.
If riderx Didn’t Receive the Invitation: Ensure that the npm username you used is correct. If there's any mistake, you can try resending the invitation.
If the process still doesn't work, try removing and re-adding the user, and ensure that riderx checks the correct npm account for the invitation.

Have you check if you got an invitation and accept it. I did the exact same procedure for my capacitor-video-player that i transfer to harmonwood and it worked fine.

**Comment by riderx** [comment]
Can you try again?
I had the same issue with GitHub, i don't receive this email, no idea why and GitHub/NPM don't know either.
So I changed my mailbox to see if that help

**Comment by jepiqueau** [comment]
@riderx i tried but i got this
queaujeanpierre@MacBook-Pro-de-Queau-Jean-Pierre ~ % npm owner ls capacitor-data-storage-sqlite
jeepq <jeanpierre.queau@gmail.com>
queaujeanpierre@MacBook-Pro-de-Queau-Jean-Pierre ~ % npm owner add riderx capacitor-data-storage-sqlite
Authenticate your account at:
https://www.npmjs.com/auth/cli/e8b83d3d-a0c1-48ab-961a-c866d3e56a32
Press ENTER to open in the browser...

npm ERR! code EOWNERMUTATE
npm ERR! Failed to update package: "409 Conflict - PUT https://registry.npmjs.org/capacitor-data-storage-sqlite/-rev/161-baa16be7758c4626aca6bea8089c05ac - User already has a pending invite"

npm ERR! A complete log of this run can be found in: /Users/queaujeanpierre/.npm/_logs/2024-08-14T17_54_43_589Z-debug-0.log

ok i delete your invitation  and redo it
if you go to [settings](https://www.npmjs.com/package/capacitor-data-storage-sqlite/access) you will see the invitation i assume you can accept it

**Comment by riderx** [comment]
It worked with the new email! Thanks !
I published new version !

**Comment by jepiqueau** [comment]
@riderx ok thank you

**Comment by riderx** [comment]
@jepiqueau Did you got any info of the repo in community?
And do you have a recommendation for 
[angular-data-storage-sqlite-app-starter](https://github.com/jepiqueau/angular-data-storage-sqlite-app-starter)
[react-data-storage-sqlite-app-starter](https://github.com/jepiqueau/react-data-storage-sqlite-app-starter)
[react-datastoragesqlite-app](https://github.com/jepiqueau/react-datastoragesqlite-app)
[vue-data-storage-sqlite-app-starter](https://github.com/jepiqueau/vue-data-storage-sqlite-app-starter)
[vue-datastoragesqlite-app](https://github.com/jepiqueau/vue-datastoragesqlite-app)

**Comment by jepiqueau** [comment]
@riderx if you wish i can transfer them to you as well but they will have to be updated and tested for the latest versions of Ionic, React, Vue. Tell me what you want

**Comment by mburger81** [comment]
@riderx using your @capgo/capacitor-data-storage-sqlite@6.0.2 I run into this issue

```
Analyzing dependencies
[capacitor]         [!] No podspec found for `CapgoCapacitorDataStorageSqlite` in `../../node_modules/@capgo/capacitor-data-storage-sqlite`
```

Looking at the Podfilethere is this `node_modules/@capgo/capacitor-data-storage-sqlite/CapacitorDataStorageSqlite.podspec` with this content

```
require 'json'

package = JSON.parse(File.read(File.join(__dir__, 'package.json')))

Pod::Spec.new do |s|
  s.name = 'CapacitorDataStorageSqlite'
  s.version = package['version']
  s.summary = package['description']
  s.license = package['license']
  s.homepage = package['repository']['url']
  s.author = package['author']
  s.source = { :git => package['repository']['url'], :tag => s.version.to_s }
  s.source_files = 'ios/Plugin/**/*.{swift,h,m,c,cc,mm,cpp}'
  s.ios.deployment_target  = '13.0'
  s.dependency 'Capacitor'
  s.dependency 'SQLite.swift/SQLCipher'
  s.swift_version = '5.1'
end
```

So its not `CapgoCapacitorDataStorageSqlite` but it's still the old `CapacitorDataStorageSqlite`

**Comment by riderx** [comment]
@jepiqueau i will do the update if you transfer them to me no problem.
@mburger81 let me check that

**Comment by riderx** [comment]
@mburger81 I realized I totally forgot that changing name in not as simple as changing the name in package.json ^^
I which it could.
So I made all the required renames in Java, and swift files. I tested the build and it works.
I think I have to write a migration doc because the change requires.
This is coming meanwhile try 6.0.4 :)

**Comment by jepiqueau** [comment]
@riderx i made the transfer of the five applications . Thank you for this

**Comment by riderx** [comment]
Thanks a lot <3

**Comment by mburger81** [comment]
@riderx can you plz have a look on this issue?
https://github.com/Cap-go/capacitor-data-storage-sqlite/issues/79

**Comment by riderx** [comment]
Jus t answered please do not continue here:)
